header:
  version: 14
  includes:
    - include/common-meta-dhsom-extras.yml

distro: fsl-imx-wayland

target:
  - imx-image-full

local_conf_header:
  standard: |
    DISTRO_FEATURES:append = " virtualization"
    IMX_DEFAULT_BSP = "nxp"
    ACCEPT_FSL_EULA = "1"
    CONF_VERSION = "2"
    # Avoid broken dependency in meta-imx layer
    BBMASK += "meta-imx/meta-bsp/recipes-bsp/u-boot/u-boot-imx-tools_2022.04.bb"
    BBMASK += "meta-imx/meta-bsp/recipes-support/opencv/opencv_4.6.0.imx.bb"
    # Avoid broken blob package QA failure in meta-imx layer
    PACKAGECONFIG:remove:pn-nnstreamer = "deepview-rt"
    ML_NNSTREAMER_PKGS_LIST:remove:pn-packagegroup-imx-ml = "nnstreamer-deepview-rt"
    ML_PKGS:remove:pn-packagegroup-imx-ml = "deepview-rt-examples"
    # Avoid broken cryptodev in meta-imx-layer
    RDEPENDS_IMX_TO_REMOVE:append:pn-packagegroup-fsl-tools-testapps = "cryptodev-module cryptodev-tests"
    # Avoid broken kernel isp-vvcam module in meta-imx-layer
    ISP_PKGS:remove:pn-packagegroup-imx-isp = "kernel-module-isp-vvcam"
    # Avoid broken scons do_compiler workaround in meta-imx layer
    EXTRA_OESCONS:remove:pn-arm-compute-library = "${SCONS_MAXLINELENGTH}"
    # Avoid broken patches in meta-freescale layer
    BBMASK += "meta-freescale/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend"
    # Repair variable append misuse in meta-imx layer.conf
    SOC_DEFAULT_IMAGE_FSTYPES:remove = "wic.bz2 tar.bz2"
    # Generate wic.xz image type along others
    SOC_DEFAULT_IMAGE_FSTYPES:append = " wic.xz"
    # Use NXP libdrm fork
    PREFERRED_PROVIDER_drm = "libdrm"
    PREFERRED_PROVIDER_libdrm = "libdrm"
    PREFERRED_PROVIDER_libdrm-native = "libdrm-native"
    PREFERRED_PROVIDER_nativesdk-libdrm = "nativesdk-libdrm"
    IMAGE_INSTALL:remove:pn-dh-image-demo = "libdrm-mainline-tests"
    IMAGE_INSTALL:remove:pn-imx-image-full = "libdrm-mainline-tests"

repos:
  meta-freescale:
    url: https://github.com/Freescale/meta-freescale

  meta-freescale-distro:
    url: https://github.com/Freescale/meta-freescale-distro

  meta-imx:
    url: https://github.com/nxp-imx/meta-imx.git
    refspec: "kirkstone-5.15.71-2.2.0"
    layers:
      meta-bsp:
      meta-ml:
      meta-sdk:

  meta-nxp-demo-experience:
    url: https://github.com/nxp-imx-support/meta-nxp-demo-experience

  meta-qt6:
    url: https://code.qt.io/yocto/meta-qt6.git
    refspec: "6.3"

  meta-virtualization:
    url: git://git.yoctoproject.org/meta-virtualization

  poky:
    layers:
      meta:
      meta-poky:
